### ISSUE TITLE
List of all clients and their associated queries.

### ISSUE THREAD

**Issue by chriscn** [chriscn/pihole-to-influxdb#3]
This seems to be possible although I am not sure how to do it yet. Might have to do some dodgy backend work. Cannot wait for PiHole to produce a coherent API.

**Comment by subDesTagesMitExtraKaese** [comment]
there doesn't seem to be official documentation on the Pi-hole API but it is easily reverse engineerable. I'd drop the pihole dependency and start implementing the requests that are issued by the GUI. It should also be possible to replace the daily totals with a accurate readings above the configured interval.

**Comment by subDesTagesMitExtraKaese** [comment]
https://github.com/chriscn/pihole-to-influxdb/commit/5e5338250194387d00bd0563b3166a090f1bf2b6 there is still some testing needed, but it satisfies all my requirements.
![grafik](https://user-images.githubusercontent.com/59580649/190287134-cb3f9904-5911-43fe-ba5b-586ebfab80c4.png)
