### ISSUE TITLE
Current build is failing

### ISSUE THREAD

**Issue by chriscn** [chriscn/pihole-to-influxdb#5]
After merging #4 - it is now failing. Should fix asap

**Comment by subDesTagesMitExtraKaese** [comment]
[python:3.9-slim-buster](https://hub.docker.com/_/python/tags?page=1&name=3.9-slim-buster) doesn't support ARMv6 anymore.

I suggest upgrading to python:3.9-slim-bullseye and using their ARMv5 build instead of ARMv6
